### PR TITLE
Updated snapshots for iOS 11.4

### PR DESCRIPTION
**Pull request by RomanTysiachnik**
Updated names for current snapshots.

@aol-public/mobile-sdk-team: Ready for review.

### CODE REVIEW

**Comment by RomanTysiachnik** [comment]
It will be able to merge it after Xcode 9.4 image will be added on Travis CI.

**Comment by AndriiMoskvin** [comment]
Do we really need to update screenshots each time new minor ios is released?

**Comment by RomanTysiachnik** [comment]
In theory - yes. But in our case, I think it's okay to update them only after every major update. I will add that ability when I will have time for that.

**Comment by RomanTysiachnik** [comment]
@AndriiMoskvin check, please.

**Pull request merged**
