### PR TITLE
Added Snapshot Testing feature

### PR DESCRIPTION
**Pull request by RomanTysiachnik**
# About
SnapshotTest is a feature, that was created to make it easier to test our view controllers on different devices and in different states using a custom UIWindow that renders our controller with chosen specifications. The main testing feature that compares two images is added from ios-snapshot-test-case by Facebook.

## Setup
First of all, you have to install our library using command 
`carthage update --platform iOS`
 There are two schemes: `Record Snapshots` and `Verify Snapshots`. You can run tests in the first scheme to record the current state of controls in snapshots or you can run them in another to compare current state with existing snapshots.

## Creating new cases
To create a new case, you have to create a new class with a new set of propositions and inherited from SnapshotTest. It should be connected to a relevant Unit tests target. If there ain't any, you should create a new one. The class name would be used in a naming of your reference images folders hierarchy. For example, if you have a target DefaultControls and a class CaseWithEmptyProgress, the name of the folder with refs/diffs will look like `DefaultControls.CaseWithEmptyProgress`.

Inside this class, you should make a test method with `verify` function call. In this method, you call method `verify` and set a `controller` that you want to test and in `Presentation` argument you pass device and it's properties. All presentations for all devices have been located in `Device` enum. There is also an optional argument that you can pass. It has type`Context`, which was created to provide an ability to set up additional trait collections, like a layout direction and a content size category.

For example: 
`verify(controller, for:  Device.iPadPro10.landscape.oneThird, in: context)`

## Launching tests
To launch tests on multiple devices, it is recommended to install Fastlane and launch tests with one of these commands:
`fastlane verify`
To record new reference images please use:
`fastlane record`
We've added a scheme that will contain both PlayerControls tests and Snapshot Tests. To run all these tests use:
`fastlane test`

## Summary of changes
Current pull-request contains next changes:
- Added SnapshotTests project without host application;
- Added two testing targets for DefaultController and AdVideoController;
- Added Cartfile;
- Implemented Fastlane and Travis.

### CODE REVIEW

**Comment by AndriiMoskvin** [comment]
What is preventing us from merging this PR?

**Comment by RomanTysiachnik** [comment]
There is an issue that we're dealing with. Our library doesn't work right now after we droped a host application and we're trying to understand this behaivor

**Comment by AndriiMoskvin** [comment]
Ok, got it.

**Comment by RomanTysiachnik** [comment]
@AndriiMoskvin We've dropped all trash and this PR should be examined and finally merged. After this one is merged, PRs with test cases should be reviewed too.

**Pull request merged**
